version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: jas0nhere/backend:latest
    container_name: backend
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres:5432/app
      - DB_USER=app
      - DB_PASS=secret
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/api/ping || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
    image: jas0nhere/frontend:latest
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
